name: Download WARN Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch: {}  # Allows manual triggering

jobs:
  download-warn-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        
      - name: Checkout data repository
        uses: actions/checkout@v4
        with:
          repository: coatless-data/warn-files
          token: ${{ secrets.DATA_REPO_PAT }}
          path: warn-data
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download WARN data
        run: |
          # Create data directory if it doesn't exist in the data repo
          mkdir -p warn-data/data
          python .github/scripts/download-warn.py warn-data/data
        
      - name: Configure Git and Push Changes
        run: |
          cd warn-data
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/*
          
          # Only commit and push if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update WARN data $(date +'%Y-%m-%d')"
            git push
          fi